application:
  version: 0.0.1
server:
  port: 8080
  max-http-header-size: 10000000 # this is required to handle the long size JWT
  servlet:
    context-path: /assignment-app
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:data;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    jdbc-url: jdbc:h2:mem:data;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS

#trn-app:
#  url-patterns:
#    - /callcenter-api/transactions/*
#    - /reconciliation/*
#  debug:
#    true
# Swagger
app:
  swagger:
    protocol: http
    host: localhost:9000
